# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bae800c52550470537a5ffa4df1ecefa2527e331857ceac8340ab9e427b7e4a659c60e803daa082e213900b19c545e0cef33548c7b9caff72768632fb48363e5

test:
  secret_key_base: d1f6a02f3e7dc54de19b425eaa78faaf0fca6ab61589e2df8c79072ae5e0350c6a7c6c86341b52e529706f07bd136523c9fe417c9343e7582fdd91405f4e8f56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
